[2025-01-22 12:06:38,576] INFO in server: Shutting down (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/server.py Line: 262)
[2025-01-22 12:06:38,677] INFO in on: Waiting for application shutdown. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 67)
[2025-01-22 12:06:38,677] INFO in on: Application shutdown complete. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 76)
[2025-01-22 12:06:38,677] INFO in server: Finished server process [8848] (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/server.py Line: 92)
[2025-01-22 13:53:39,976] INFO in server: Started server process [13530] (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/server.py Line: 82)
[2025-01-22 13:53:39,989] INFO in on: Waiting for application startup. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 48)
[2025-01-22 13:53:39,990] INFO in on: Application startup complete. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 62)
[2025-01-22 13:54:09,535] INFO in httptools_impl: 127.0.0.1:33910 - "GET / HTTP/1.1" 200 (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py Line: 468)
[2025-01-22 13:54:17,311] INFO in server: Shutting down (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/server.py Line: 262)
[2025-01-22 13:54:17,411] INFO in on: Waiting for application shutdown. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 67)
[2025-01-22 13:54:17,411] INFO in on: Application shutdown complete. (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/lifespan/on.py Line: 76)
[2025-01-22 13:54:17,411] INFO in server: Finished server process [13530] (File: /home/ernesto/anaconda3/envs/ts_dashboard/lib/python3.11/site-packages/uvicorn/server.py Line: 92)
